apiVersion: v1
kind: ServiceAccount
metadata:
name: wiz-robot-sa
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: wiz-robot-admin-binding
subjects:

kind: ServiceAccount
name: wiz-robot-sa
namespace: default
roleRef:
kind: ClusterRole
name: cluster-admin
apiGroup: rbac.authorization.k8s.io
